# housingxyz-provider :: azure-devops

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: 'build'
    displayName: 'build'
    jobs:
      - job:
        displayName: 'build::aspnet'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
              cd aspnet
              dotnet build

  - stage: 'pack'
    condition: succeeded('build')
    dependsOn:
      - build
    displayName: 'pack'
    jobs:
      - job:
        displayName: 'pack::aspnet'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker login'
          - script: |
              docker image build -f .docker/dockerfile -t housingxyz-provider .
            displayName: 'docker build'
          - script: |
              docker image tag housingxyz-provider revaturexyz/housingxyz-provider:pre
              docker image push revaturexyz/housingxyz-provider:pre
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/broker'))
            displayName: 'docker push::pre'
          - script: |
              docker image tag housingxyz-provider revaturexyz/housingxyz-provider:dev
              docker image push revaturexyz/housingxyz-provider:dev
            condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
            displayName: 'docker push::dev'
          - script: |
              docker image tag housingxyz-provider revaturexyz/housingxyz-provider:stg
              docker image push revaturexyz/housingxyz-provider:stg
            condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
            displayName: 'docker push::stg'
          - task: Docker@2
            inputs:
              command: 'logout'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker logout'

trigger:
  branches:
    include:
      - master
      - broker
  tags:
    include:
      - '*'

variables:
  - group: azure.vars
  - group: cloudflare.vars
  - group: sonarcloud.vars
