# housingxyz-provider :: azure-devops

name: $(date:yyyyMMdd)$(rev:.rr)

stages:
  - stage: 'build'
    displayName: 'build'
    jobs:
      - job:
        displayName: 'build::aspnet'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - script: |
             cd aspnet
             dotnet build

  - stage: 'pack'
    condition: succeeded('build')
    dependsOn:
      - build
    displayName: 'pack'
    jobs:
      - job:
        displayName: 'pack::aspnet'
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: Docker@2
            inputs:
              command: 'login'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker login'
          - script: |
              docker image build -f .docker/dockerfile -t housingxyz-provider .
            displayName: 'docker build'
          - task: Docker@2
            inputs:
              command: 'logout'
              containerRegistry: 'revaturexyz-docker'
            displayName: 'docker logout'

  - stage: 'pre'
    condition: succeeded('pack')
    dependsOn:
      - pack
    displayName: 'pre'

  - stage: 'dev'
    condition: succeeded('pack')
    dependsOn:
      - pack
    displayName: 'dev'

  - stage: 'stg'
    condition: succeeded('pack')
    dependsOn:
      - pack
    displayName: 'stg'

trigger:
  branches:
    include:
      - master
      - broker
  tags:
    include:
      - '*'

variables:
  - group: azure.vars
  - group: cloudflare.vars
  - group: sonarcloud.vars
